import {
    Wifi,
    Wind,
    Tv,
    Coffee,
    UtensilsCrossed,
    Shirt,
    PawPrint,
    Bed,
    Heart,
    Lock,
    AlertCircle,
    Flame,
    Wine,
    Snowflake,
    Table,
    Sun,
    CheckCircle,
    Bath,
    type LucideIcon,
} from "lucide-react";
import type { Amenity } from "@/content/apartments";

export const amenityIcons: Record<Amenity, LucideIcon> = {
    Wifi,
    "Air Conditioning": Wind,
    TV: Tv,
    "Coffee Maker": Coffee,
    "Full Kitchen": UtensilsCrossed,
    Dryer: Shirt,
    Washer: Shirt,
    "Pet Friendly": PawPrint,
    "Outdoor Furniture": Sun,
    "Hair Dryer": Wind,
    Bedding: Bed,
    Bidet: Bath,
    Kettle: Flame,
    "Wine Glasses": Wine,
    Freezer: Snowflake,
    "Ethernet Connection": Wifi,
    Kitchen: UtensilsCrossed,
    "Extra Pillows and Blankets": Bed,
    "Fire Extinguisher": AlertCircle,
    Iron: Shirt,
    Stove: Flame,
    Oven: Flame,
    Fridge: Snowflake,
    Hangers: Shirt,
    "Private Entrance": Lock,
    "First Aid Kit": Heart,
    "Coffee Machine": Coffee,
    "Patio or Balcony": Sun,
    "Dishes and Cutlery": UtensilsCrossed,
    "Cleaning Products": Wind,
    "Carbon Monoxide Detector": AlertCircle,
    Heating: Flame,
    "Body Soap": Bath,
    "Basic Services": CheckCircle,
    "Basic Cooking Services": UtensilsCrossed,
    "Dining Table": Table,
    "Baking Tray": Flame,
    "Outdoor Dining Area": Sun,
};
